import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";
import Toast from "@/components/Toast";
import SideBar from "./(components)/SideBar";
import SocketClient from "@/components/SocketClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider>
          <SocketClient>
            <div className="flex h-screen w-screen items-stretch overflow-hidden">
              <SideBar />
              <div className="flex-1">{children}</div>
            </div>
          </SocketClient>
        </AuthProvider>
        <Toast />
      </body>
    </html>
  );
}
